import APISidebar from "./components/Sidebar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import './api.css'

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <div className="container">
          <APISidebar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  )
}
